Remove traces of obsolete dependences from virtualenv
freedomofpress/securedrop pull request #5487
Opened 2020-09-09 16:19 UTC by rmol

## Status

Ready for review

## Description of Changes

After removing a dependency from the securedrop-app-code requirements, its byte code files could be left behind after installation of the updated package. This adds a function in postinst to clean those up.

Fixes #856.

## Testing

- Build a staging environment. 
- Once complete, log in to the app server and list the contents of a requirement which we'll delete:
`ls -alR /opt/venvs/securedrop-app-code/lib/python3.5/site-packages/psutil`
  There should be `.pyc` files there.
- Back in your working copy, comment out the `psutil` lines in `securedrop/requirements/python3/securedrop-app-code-requirements.txt`, rerun `make build-debs` and `make staging`.
- On the app server, list the `psutil` path above. There should be no `.pyc` files.

## Deployment

This removes all Python byte code from the virtualenv, to purge obsolete requirements. 

## Checklist

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

2020-09-14 13:26 UTC, kushaldas requested changes
I can still see `pyc` files. 

```
vagrant@app-staging:~$ ls -alR /opt/venvs/securedrop-app-code/lib/python3.5/site-packages/psutil
/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/psutil:
total 12
drwxr-xr-x  3 root root 4096 Sep 14 13:07 .
drwxr-xr-x 79 root root 4096 Sep 14 13:07 ..
drwxr-xr-x  2 root root 4096 Sep 14 12:30 __pycache__

/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/psutil/__pycache__:
total 168
drwxr-xr-x 2 root root  4096 Sep 14 12:30 .
drwxr-xr-x 3 root root  4096 Sep 14 13:07 ..
-rw-r--r-- 1 root root 22578 Sep 14 12:30 _common.cpython-35.pyc
-rw-r--r-- 1 root root 10936 Sep 14 12:30 _compat.cpython-35.pyc
-rw-r--r-- 1 root root 67587 Sep 14 12:30 __init__.cpython-35.pyc
-rw-r--r-- 1 root root 52664 Sep 14 12:30 _pslinux.cpython-35.pyc
-rw-r--r-- 1 root root  4018 Sep 14 12:30 _psposix.cpython-35.pyc
```

2020-09-17 00:02 UTC, eloquence commented
@rmol is this ready for re-review?

2020-09-17 17:39 UTC, rmol commented
Yeah, I've tried again in both Qubes and libvirt staging environments and can't repro the failure; the directory is always cleaned out.

2020-09-21 12:24 UTC, kushaldas commented
I am trying again today

2020-09-21 14:29 UTC, kushaldas approved these changes
The current code works. 

- [x] No `.pyc` files left from `psutils` module after removing it following the steps.

2020-09-21 14:29 UTC, merged