Updates pytest pluggy testinfra molecule and the universe
freedomofpress/securedrop pull request #5585
Opened 2020-10-15 14:48 UTC by kushaldas

## Status

Work in progress

## Description of Changes

Fixes #5584

### Changes still left do be done in this PR

- [ ] Update pytest markers

```
    ../testinfra/common/test_grsecurity.py:129
    ../testinfra/common/test_grsecurity.py:129
    ../testinfra/common/test_grsecurity.py:129
    ../testinfra/common/test_grsecurity.py:129
      /root/code/securedrop/molecule/testinfra/common/test_grsecurity.py:129: PytestUnknownMarkWarning: Unknown pytest.mark.skip_in_prod - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
        @pytest.mark.skip_in_prod
    
    ../testinfra/common/test_user_config.py:89
    ../testinfra/common/test_user_config.py:89
    ../testinfra/common/test_user_config.py:89
    ../testinfra/common/test_user_config.py:89
      /root/code/securedrop/molecule/testinfra/common/test_user_config.py:89: PytestUnknownMarkWarning: Unknown pytest.mark.skip_in_prod - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
        @pytest.mark.skip_in_prod

```

## Testing

We have to test each and every scenario. Note: we have to update each of the below points with proper test steps.

- [ ] builder-focal
- [ ] builder-xenial
- [ ] fetch-tor-packages
- [ ] molecule test -s libvirt-staging-xenial 
- [ ] molecule test -s libvirt-staging-focal
- [ ] molecule converge -s qubes-staging

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

## Checklist

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

### If you made changes to documentation:

- [ ] Doc linting (`make docs-lint`) passed locally

### If you added or updated a code dependency:

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

2020-10-21 16:13 UTC, emkll requested changes
Thanks @kushaldas , went though the test plan and observe a few failures in some scenarios. Also, I did not test all the cases (Qubes and Virtualbox scenarios)
- [x] make build-debs
- [x] make build-debs-focal
- [x] make fetch-tor-packages
- [x] molecule test -s libvirt-staging-xenial 
- [x] molecule test -s libvirt-staging-focal
- [ ] molecule converge virtualbox-staging-xenial (did not test)
- [ ] molecule converge -s qubes-staging-focal (did not test)
- [ ] molecule converge -s qubes-staging-xenial (did not test)
- :exclamation:  `make testinfra` on prod VMs looks like testinfra version needs to be updated in https://github.com/freedomofpress/securedrop/blob/updates_pytest_pluggy_testinfra_molecule_and_the_universe/admin/requirements-testinfra.txt
- :exclamation:  `make upgrade-start` Molecule syntax error
- :exclamation:  `make upgrade test-local` can't run because start command above doesn't work
- :exclamation:  `make upgrade-start-qa`Molecule syntax error
- :exclamation:  `make upgrade-test-qa` cant run because start command above doesn't work

2020-10-21 22:49 UTC, zenmonkeykstop commented
Confirmed that the following pass:
- [x] molecule converge -s qubes-staging-focal 
- [x] molecule converge -s qubes-staging-xenial

2020-10-27 12:03 UTC, kushaldas commented
`playbook.yml was deprecated, rename it to converge.yml` 

Wondering if I should update this? @emkll what do you think?

2020-10-27 13:38 UTC, emkll commented
It seems like it just consists of renaming the files, I think it's worth addressing as part of this PR, good catch

2020-10-28 15:31 UTC, emkll commented
Hey @kushaldas was just testing the libvirt-focal scenario, is it expected that tests not run? 

After running `molecule converge -s libvirt-staging-focal` and running `molecule verify -s libvirt-staging-focal`, the verify command returns non-zero with the following output:

```
--> Executing Testinfra tests found in /home/m/src/securedrop/molecule/libvirt-staging-focal/../testinfra/...
    ============================= test session starts ==============================
    platform linux -- Python 3.7.3, pytest-6.1.1, py-1.9.0, pluggy-0.13.1 -- /home/m/.virtualenvs/securedrop/bin/python3
    rootdir: /home/m/src/securedrop/molecule, configfile: pytest.ini
    plugins: testinfra-5.3.1, forked-1.3.0, xdist-2.1.0
[gw0] linux Python 3.7.3 cwd: /home/m/src/securedrop/molecule/libvirt-staging-focal
[gw1] linux Python 3.7.3 cwd: /home/m/src/securedrop/molecule/libvirt-staging-focal
gw0 C / gw1 C[gw0] node down: Traceback (most recent call last):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
        do_exec(co, loc)  # noqa
      File "<string>", line 1, in do_exec
      File "<remote exec>", line 14, in <module>
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/__init__.py", line 3, in <module>
        from . import collect
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/collect.py", line 4, in <module>
        from typing import Any
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1347, in <module>
        class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1003, in __new__
        self._abc_registry = extra._abc_registry
    AttributeError: type object 'Callable' has no attribute '_abc_registry'
    
    
    replacing crashed worker gw0
[gw2] linux Python 3.7.3 cwd: /home/m/src/securedrop/molecule/libvirt-staging-focal
gw2 C / gw1 C[gw1] node down: Traceback (most recent call last):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
        do_exec(co, loc)  # noqa
      File "<string>", line 1, in do_exec
      File "<remote exec>", line 14, in <module>
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/__init__.py", line 3, in <module>
        from . import collect
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/collect.py", line 4, in <module>
        from typing import Any
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1347, in <module>
        class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1003, in __new__
        self._abc_registry = extra._abc_registry
    AttributeError: type object 'Callable' has no attribute '_abc_registry'
    
    
    replacing crashed worker gw1
[gw3] linux Python 3.7.3 cwd: /home/m/src/securedrop/molecule/libvirt-staging-focal
gw2 C / gw3 C[gw2] node down: Traceback (most recent call last):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
        do_exec(co, loc)  # noqa
      File "<string>", line 1, in do_exec
      File "<remote exec>", line 14, in <module>
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/__init__.py", line 3, in <module>
        from . import collect
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/collect.py", line 4, in <module>
        from typing import Any
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1347, in <module>
        class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1003, in __new__
        self._abc_registry = extra._abc_registry
    AttributeError: type object 'Callable' has no attribute '_abc_registry'
    
    
    replacing crashed worker gw2
[gw4] linux Python 3.7.3 cwd: /home/m/src/securedrop/molecule/libvirt-staging-focal
gw4 C / gw3 C[gw3] node down: Traceback (most recent call last):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
        do_exec(co, loc)  # noqa
      File "<string>", line 1, in do_exec
      File "<remote exec>", line 14, in <module>
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/__init__.py", line 3, in <module>
        from . import collect
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/collect.py", line 4, in <module>
        from typing import Any
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1347, in <module>
        class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1003, in __new__
        self._abc_registry = extra._abc_registry
    AttributeError: type object 'Callable' has no attribute '_abc_registry'
    
    
    replacing crashed worker gw3
[gw5] linux Python 3.7.3 cwd: /home/m/src/securedrop/molecule/libvirt-staging-focal
gw4 C / gw5 C[gw4] node down: Traceback (most recent call last):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
        do_exec(co, loc)  # noqa
      File "<string>", line 1, in do_exec
      File "<remote exec>", line 14, in <module>
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/__init__.py", line 3, in <module>
        from . import collect
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/collect.py", line 4, in <module>
        from typing import Any
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1347, in <module>
        class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1003, in __new__
        self._abc_registry = extra._abc_registry
    AttributeError: type object 'Callable' has no attribute '_abc_registry'
    
    
    replacing crashed worker gw4
[gw6] linux Python 3.7.3 cwd: /home/m/src/securedrop/molecule/libvirt-staging-focal
gw6 C / gw5 C[gw5] node down: Traceback (most recent call last):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
        do_exec(co, loc)  # noqa
      File "<string>", line 1, in do_exec
      File "<remote exec>", line 14, in <module>
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/__init__.py", line 3, in <module>
        from . import collect
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/pytest/collect.py", line 4, in <module>
        from typing import Any
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1347, in <module>
        class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/typing.py", line 1003, in __new__
        self._abc_registry = extra._abc_registry
    AttributeError: type object 'Callable' has no attribute '_abc_registry'
    
    
    replacing crashed worker gw5
[gw7] linux Python 3.7.3 cwd: /home/m/src/securedrop/molecule/libvirt-staging-focal
gw6 C / gw7 C[gw6] node down: Traceback (most recent call last):
      File "/home/m/.virtualenvs/securedrop/lib/python3.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
        do_exec(co, loc)  # noqa
      File "<string>", li [...]

2020-10-28 15:36 UTC, kushaldas commented
@emkll can you please paste the output of `python3 -m pip list` from the virtualenv on the host machine?

2020-10-28 15:41 UTC, emkll commented
```
Package             Version    
------------------- -----------
alembic             0.9.9      
ansible             2.9.7      
ansible-lint        4.2.0      
apipkg              1.4        
argon2-cffi         20.1.0     
arrow               0.10.0     
asn1crypto          0.22.0     
aspy.yaml           1.3.0      
astroid             2.4.0      
attrs               20.2.0     
Babel               2.5.1      
bandit              1.4.0      
bcrypt              3.1.3      
binaryornot         0.4.4      
boto                2.48.0     
boto3               1.5.24     
botocore            1.8.38     
Cerberus            1.3.1      
certifi             2017.7.27.1
cffi                1.14.2     
cfgv                2.0.1      
chardet             3.0.4      
click               7.1.2      
click-completion    0.5.2      
click-help-colors   0.8        
colorama            0.3.9      
cookiecutter        1.6.0      
cryptography        2.7        
distro              1.5.0      
dnspython           1.15.0     
docker-py           1.10.6     
docker-pycreds      0.2.1      
docopt              0.6.2      
docutils            0.14       
dparse              0.4.1      
entrypoints         0.3        
execnet             1.4.1      
fasteners           0.14.1     
flake8              3.7.7      
Flask               1.0.2      
Flask-Assets        0.12       
Flask-Babel         0.11.2     
Flask-SQLAlchemy    2.4.0      
Flask-WTF           0.14.2     
future              0.16.0     
git-url-parse       1.0.2      
gitdb2              2.0.3      
GitPython           2.1.8      
html-linter         0.4.0      
identify            1.4.7      
idna                2.5        
importlib-metadata  0.23       
importlib-resources 1.5.0      
iniconfig           1.0.1      
isort               4.2.15     
itsdangerous        0.24       
Jinja2              2.10.1     
jinja2-time         0.2.0      
jmespath            0.9.3      
jsmin               2.2.2      
lazy-object-proxy   1.4.3      
Mako                1.0.7      
MarkupSafe          1.1.1      
mccabe              0.6.1      
mod-wsgi            4.6.7      
molecule            3.0.2.1    
molecule-vagrant    0.3        
monotonic           1.4        
more-itertools      7.2.0      
mypy                0.761      
mypy-extensions     0.4.3      
netaddr             0.7.19     
nodeenv             1.3.3      
packaging           16.8       
paramiko            2.6.0      
passlib             1.7.1      
pathspec            0.5.5      
pbr                 5.1.1      
pexpect             4.6.0      
pip                 19.3.1     
pip-tools           4.5.1      
pkg-resources       0.0.0      
pluggy              0.13.1     
poyo                0.4.1      
pre-commit          1.18.3     
pretty-bad-protocol 3.1.1      
prompt-toolkit      2.0.9      
psutil              5.7.0      
ptyprocess          0.5.2      
py                  1.9.0      
pycodestyle         2.5.0      
pycparser           2.18       
pyenchant           2.0.0      
pyflakes            2.1.1      
pylint              2.5.0      
PyNaCl              1.1.2      
pyotp               2.2.6      
pyparsing           2.2.0      
pytest              6.1.1      
pytest-forked       1.3.0      
pytest-xdist        2.1.0      
python-dateutil     2.6.1      
python-editor       1.0.3      
python-gilt         1.2.1      
python-vagrant      0.5.15     
pytz                2017.3     
PyYAML              5.3.1      
qrcode              5.3        
redis               3.3.6      
requests            2.22.0     
rq                  1.1.0      
ruamel.yaml         0.16.10    
ruamel.yaml.clib    0.2.0      
s3transfer          0.1.12     
safety              1.8.7      
scrypt              0.8.0      
selinux             0.2.1      
setuptools          46.0.0     
sh                  1.12.14    
shellingham         1.3.2      
six                 1.15.0     
smmap2              2.0.3      
SQLAlchemy          1.3.3      
stevedore           1.28.0     
tabulate            0.8.7      
template-remover    0.1.9      
testinfra           5.3.1      
toml                0.10.0     
tree-format         0.1.2      
typed-ast           1.4.1      
typing              3.6.4      
typing-extensions   3.7.4.1    
urllib3             1.25.10    
virtualenv          16.7.5     
wcwidth             0.1.7      
webassets           0.12.1     
websocket-client    0.44.0     
Werkzeug            0.16.0     
wheel               0.35.1     
whichcraft          0.4.1      
wrapt               1.11.2     
WTForms             2.1        
yamllint            1.17.0     
zipp                0.6.0 
```

2020-10-28 15:44 UTC, kushaldas commented
>`typing              3.6.4 `

This is the problem, as the host is already Python3.7 on Buster. @emkll can you please create a fresh virtualenv and install develop-requirements.txt from this branch and try?

2020-10-28 15:44 UTC, rmol commented
I ran through all the test scenarios. All but `libvirt-staging-focal` eventually completed without errors, but `qubes-staging-xenial` fails pretty consistently the first time through, because of an apt lock error on the mon server. 

- [x] make build-debs
- [x] make build-debs-focal
- [x] make fetch-tor-packages
- [x] molecule test -s libvirt-staging-xenial 
- [ ] molecule test -s libvirt-staging-focal

  :face_with_head_bandage: Repeatable errors:

  <details>
  <summary>Provisioning errors: ossec packages can't be installed because of dependency problems, but this is ignored.</summary>

  ```
      failed: [mon-staging] (item=[2, 'securedrop-ossec-server-3.6.0+1.7.0~rc1-amd64.deb']) => {"ansible_loop_var": "item", "changed": false, "item": [2, "securedrop-ossec-server-3.6.0+1.7.0~rc1-amd64.deb"], "msg": "Dependency is not satisfiable: ossec-server\n"}
      failed: [app-staging] (item=[2, 'securedrop-ossec-agent-3.6.0+1.7.0~rc1-amd64.deb']) => {"ansible_loop_var": "item", "changed": false, "item": [2, "securedrop-ossec-agent-3.6.0+1.7.0~rc1-amd64.deb"], "msg": "Dependency is not satisfiable: ossec-agent\n"}
  ```
  </details>

  <details>
  <summary>Five test errors</summary>

  ```=================================== FAILURES ===================================
      __________ test_listening_ports[ansible://mon-staging-ossec_service1] __________
      [gw2] linux -- Python 3.7.3 /home/user/src/fpf/securedrop/.venv/bin/python3
    
      host = <testinfra.host.Host ansible://mon-staging>
      ossec_service = {'host': '0.0.0.0', 'listening': True, 'port': 1514, 'proto': 'udp'}
    
        @pytest.mark.skip_in_prod
        @pytest.mark.parametrize('ossec_service', [
            dict(host="0.0.0.0", proto="tcp", port=22, listening=True),
            dict(host="0.0.0.0", proto="udp", port=1514, listening=True),
            dict(host="0.0.0.0", proto="tcp", port=1515, listening=False),
        ])
        def test_listening_ports(host, ossec_service):
            """
            Ensure the OSSEC-related services are listening on the
            expected sockets. Services to check include ossec-remoted
            and ossec-authd. Helper services such as postfix are checked
            separately.
    
            Note that the SSH check will fail if run against a prod host, due
            to the SSH-over-Tor strategy. We can port the parametrized values
            to config test YAML vars at that point.
            """
            socket = "{proto}://{host}:{port}".format(**ossec_service)
            with host.sudo():
                # Really hacky work-around for bug found in testinfra 1.12.0
                # https://github.com/philpep/testinfra/issues/311
                if "udp" in socket:
                    lsof_socket = "{proto}@{host}:{port}".format(**ossec_service)
                    udp_check = host.run("lsof -n -i"+lsof_socket)
    
                    if ossec_service['listening']:
    >                   assert udp_check.rc == 0
    E                   assert 1 == 0
    E                     +1
    E                     -0
    
    ../testinfra/mon/test_mon_network.py:76: AssertionError
    _________ test_apparmor_enforced[ansible://app-staging-/sbin/dhclient] _________
    [gw2] linux -- Python 3.7.3 /home/user/src/fpf/securedrop/.venv/bin/python3
    
    host = <testinfra.host.Host ansible://app-staging>
    aa_enforced = '/sbin/dhclient'
    
        @pytest.mark.parametrize('aa_enforced', sdvars.apparmor_enforce)
        def test_apparmor_enforced(host, aa_enforced):
            awk = ("awk '/[0-9]+ profiles.*enforce./"
                   "{flag=1;next}/^[0-9]+.*/{flag=0}flag'")
            with host.sudo():
                c = host.check_output("aa-status | {}".format(awk))
    >           assert aa_enforced in c
    E           AssertionError: assert '/sbin/dhclient' in '   /usr/bin/man\n   /usr/lib/NetworkManager/nm-dhcp-client.action\n   /usr/lib/NetworkManager/nm-dhcp-helper\n   /usr...bin/dhclient\n   lsb_release\n   man_filter\n   man_groff\n   nvidia_modprobe\n   nvidia_modprobe//kmod\n   system_tor'
    
    ../testinfra/app/test_apparmor.py:102: AssertionError
    ________________ test_gpg_key_in_keyring[ansible://app-staging] ________________
    [gw3] linux -- Python 3.7.3 /home/user/src/fpf/securedrop/.venv/bin/python3
    
    host = <testinfra.host.Host ansible://app-staging>
    
        @pytest.mark.skip_in_prod
        def test_gpg_key_in_keyring(host):
            """ ensure test gpg key is present in app keyring """
            with host.sudo(sdvars.securedrop_user):
                c = host.run("gpg --homedir /var/lib/securedrop/keys "
                             "--list-keys 28271441")
    >           assert "pub   4096R/28271441 2013-10-12" in c.stdout
    E           assert 'pub   4096R/28271441 2013-10-12' in 'pub   rsa4096 2013-10-12 [SC]\n      65A1B5FF195B56353CC63DFFCC40EF1228271441\nuid           [ unknown] SecureDrop Test/Development (DO NOT USE IN PRODUCTION)\nsub   rsa4096 2013-10-12 [E]\n\n'
    E            +  where 'pub   rsa4096 2013-10-12 [SC]\n      65A1B5FF195B56353CC63DFFCC40EF1228271441\nuid           [ unknown] SecureDrop Test/Development (DO NOT USE IN PRODUCTION)\nsub   rsa4096 2013-10-12 [E]\n\n' = CommandResult(command=b"sudo -u www-data /bin/sh -c 'gpg --homedir /var/lib/securedrop/keys --list-keys 28271441'", ex...96 2013-10-12 [E]\n\n', stderr=b"Warning: Permanently added '192.168.121.149' (ECDSA) to the list of known hosts.\r\n").stdout
    
    ../testinfra/app/test_appenv.py:75: AssertionError
    _____________ test_fpf_apt_repo_fingerprint[ansible://app-staging] _____________
    [gw0] linux -- Python 3.7.3 /home/user/src/fpf/securedrop/.venv/bin/python3
    
    host = <testinfra.host.Host ansible://app-staging>
    
        def test_fpf_apt_repo_fingerprint(host):
            """
            Ensure the FPF apt repo has the correct fingerprint on the associated
            signing pubkey. The key changed in October 2016, so test for the
            newest fingerprint, which is installed on systems via the
            `securedrop-keyring` package.
            """
    
            c = host.run('apt-key finger')
    
            fpf_gpg_pub_key_info = """/etc/apt/trusted.gpg.d/securedrop-keyring.gpg
        ---------------------------------------------
        pub   4096R/00F4AD77 2016-10-20 [expires: 2021-06-30]
              Key fingerprint = 2224 5C81 E3BA EB41 38B3  6061 310F 5612 00F4 AD77
        uid                  SecureDrop Release Signing Key"""
    
            assert c.rc == 0
    >       assert fpf_gpg_pub_key_info in c.stdout
    E       assert '/etc/apt/trusted.gpg.d/securedrop-keyring.gpg\n---------------------------------------------\npub   4096R/00F4AD77 20... fingerprint = 2224 5C81 E3BA EB41 38B3  6061 310F 5612 00F4 AD77\nuid                  SecureDrop Release Signing Key' in '/etc/apt/trusted.gpg.d/securedrop-keyring.gpg\n---------------------------------------------\npub   rsa4096 2016-10-2...2 8719 20D1 991B C93C\nuid           [ unknown] Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>\n\n'
    E        +  where '/etc/apt/trusted.gpg.d/securedrop-keyring.gpg\n---------------------------------------------\npub   rsa4096 2016-10-2...2 8719 20D1 991B C93C\nuid           [ unknown] Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>\n\n' = CommandResult(command=b'apt-key finger', exit_status=0, stdout=b'/etc/apt/trusted.gpg.d/securedrop-keyring.gpg\n------...149' (ECDSA) to the list of known hosts.\r\nWarning: apt-key output should not be parsed (stdout is not a terminal)\n").stdout
    
    ../testinfra/common/test_fpf_apt_repo.py:55: AssertionError
    _____________ test_fpf_apt_repo_fingerprint[ansible://mon-staging] _____________
    [gw1] linux -- Python 3.7.3 /home/user/src/fpf/securedrop/.venv/bin/python3
    
    host = <testinfra.host.Host ansible://mon-staging>
    
        def test_fpf_apt_repo_fingerprint(host) [...]

2020-10-28 15:53 UTC, emkll commented
> This is the problem, as the host is already Python3.7 on Buster. @emkll can you please create a fresh virtualenv and install develop-requirements.txt from this branch and try?

That worked, thanks! My mistake was installing the updated requirements in an existing virtualenv. Developers will need to recreate a new virtualenv or manually remove `typing` from the virtualenv

2020-10-28 21:14 UTC, rmol commented
I retried the failures on `develop`:
- `molecule test -s libvirt-staging-focal` had exactly the same failures.
- `molecule converge virtualbox-staging-xenial` worked perfectly two times in a row. I can't see any difference in our code that would explain this.
- `molecule converge -s qubes-staging-xenial` worked perfectly once, then the second run had the same apt lock error.

I'm inclined to merge this and address the failures separately, since two out of three are happening on `develop` and the other, if it isn't in fact a flake, only affects a staging environment that's on the way out (Virtualbox and Xenial).

2020-10-28 22:09 UTC, emkll approved these changes
Based on @rmol and @zenmonkeykstop 's review, I second @rmol 's comment, good to merge as-is, to unblock work on Focal. Let's identify any problems that may arise from these major version bumps, and open follow-up issues as needed

All changes here are to test requirements and therefore should not need a diff review.

2020-10-28 22:10 UTC, merged