Fixes #5676 disable v2 onion addresses on restore on Focal
freedomofpress/securedrop pull request #5677
Opened 2020-12-17 14:29 UTC by kushaldas

## Status

Ready for review / Work in progress

## Description of Changes

Fixes #5676 

We filter out any v2 onion address related line from /etc/tor/torrc
and also the directories from /var/lib/tor/services. This will
happen only on Focal. On Xenial, everything stays the same.

## Testing

- [ ] Checkout this branch in Tails
- [ ] Restore a v2 + v3 backup into a Xenial prod, nothing should change
- [ ] Create a Focal prod vm following steps at https://github.com/freedomofpress/securedrop/pull/5669 with both v2+v3
- [ ] Restore the same backup from tails to the Focal VM.

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

## Checklist

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [ ] These changes do not require documentation

### If you added or updated a code dependency:

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

2021-01-21 00:42 UTC, eloquence commented
(Marked as release blocker for 1.8.0.)

2021-02-10 17:04 UTC, kushaldas commented
Rebased today.

2021-02-11 20:46 UTC, rmol requested changes, later dismissed
This left Xenial services untouched. On Focal it removed all v2 services but ssh. Seems like that should go as well.

2021-02-17 12:45 UTC, kushaldas commented
I started working on the updating of the PR, and now wondering about the scenario of `v2 ssh`. My update will assume that `v3 ssh` is already setup.

2021-02-17 12:51 UTC, kushaldas commented
Rebased against develop.

2021-02-22 22:38 UTC, zenmonkeykstop commented
Tried using this to restore a v2+v3 Xenial backup onto a v3-only Focal system. It fails at the compare_torrc.py step, as the configurations are obviously different, but this scenario should probably be supported.

My expectation would be that the migration states should go as follows:

|  backup \ target     | v2 Xenial |         v2+v3 Xenial          |       v3 Xenial        |        v3 Focal         |
|-------|-----------|-------------------------------|------------------------|-------------------------|
| v2    | Yes       | No (restore *then* migrate) | yes with --skip-tor    | yes with --skip-tor     |
| v2+v3 | No        | Yes                           | yes but v3-only (arg?) | yes but v3-only (arg?)  |
| v3    | No        | Yes but v3-only (arg?)        | Yes                    | Yes                     |

- The v2 backup row is covered with current code.
- The v2+v3 backup row is *not* covered, needs changes to compare_torrc.py logic and/or an extra argument to make the v3-only thing explicit
- the v3 backup row is *not* covered, needs same changes as v2+v3

In all cases the docs need refreshing (see https://github.com/freedomofpress/securedrop-docs/pull/133 ).

We can probably get away without the script to clean up the servers' `torrc` files as the install playbook is run as part of migrations and it can ensure that `torrc` is correct.

2021-02-24 13:28 UTC, kushaldas commented
I tested with v2/v3 and only v3 restore. Also fixed the merge conflict in CI. Now, need at least more person to make sure that I did not loose anything after merge conflict. Maybe @zenmonkeykstop

2021-02-24 16:31 UTC, zenmonkeykstop approved these changes
Conflict resolution looks good based on visual review. Approving.

2021-02-24 17:04 UTC, merged