Added checksum validation for codecov scripts
freedomofpress/securedrop pull request #5907
Opened 2021-04-19 19:31 UTC by zenmonkeykstop

## Status

Ready for review 

## Description of Changes

Updates codecov `bash` and `env` script calls in CI to validate checksums against their GitHub repo before running.

## Testing

- [ ] CI is passing
- [ ] codecov scripts used in `securedrop/bin/{run-test,dev-shell} are not piped directly into bash 

## Deployment

CI only, no deployment issues

2021-04-21 17:57 UTC, conorsch requested changes
Since this PR was opened, looks like we have more checksums to validate. Will tack on some changes requested and confirm CI is still passing.

2021-04-21 17:57 UTC, conorsch commented on securedrop/bin/dev-shell
> +        curl -s https://codecov.io/env > "$tmpdir"/env;
> env isn't in SHA256SUM yet!!

Looks like it is now: https://github.com/codecov/codecov-bash/blob/1b4b96ac38946b20043b3ca3bad88d95462259b6/SHA256SUM

2021-04-21 17:57 UTC, conorsch commented on .circleci/config.yml
> +      image: ubuntu-2004:202010-01
Machine images are set to 20.04 through all machine-executor jobs in the CI config. :+1:

2021-04-21 17:57 UTC, conorsch commented on securedrop/bin/dev-shell
> +        VERSION=$(curl --silent "https://api.github.com/repos/codecov/codecov-bash/releases/latest" | grep '"tag_name":' |sed -E 's/.*"([^"]+)".*/\1/')
Suggestion: `curl -s https://api.github.com/repos/codecov/codecov-bash/releases/latest | jq -r .tag_name` for posterity's sake.

2021-04-21 17:57 UTC, conorsch commented on securedrop/bin/dev-shell
> +        chmod +x "$tmpdir"/env
Nit: does `env` need to be executable?

2021-04-22 00:28 UTC, conorsch commented
Encountered a flake on the ua test:

```
assert 1 == 0
  +1
  -0
host = <testinfra.host.Host ansible://app-staging>

    def test_unattended_upgrades_functional(host):
        """
        Ensure unatteded-upgrades completes successfully and ensures all packages
        are up-to-date.
        """
        if host.system_info.codename != "xenial":
            c = host.run('sudo unattended-upgrades --dry-run --debug')
>           assert c.rc == 0
E           assert 1 == 0
E             +1
E             -0

../testinfra/common/test_automatic_updates.py:256: AssertionError
```

via https://app.circleci.com/pipelines/github/freedomofpress/securedrop/2313/workflows/1e215457-a0bd-4e8f-9aec-2c800348d61b/jobs/53583 . Rerunning.

2021-04-22 00:28 UTC, conorsch approved these changes

2021-04-22 14:33 UTC, emkll approved these changes
CI now passing, and changes lgtm

2021-04-22 14:33 UTC, merged