Move reply key generation to /submit endpoint
freedomofpress/securedrop pull request #6490
Opened 2022-07-18 17:03 UTC by zenmonkeykstop

## Status

Work in progress

## Description of Changes

Fixes #6489 6489

Reply key generation is moved in the SI from `/lookup` to `/submit`. If a key is not already present for the given source it will be created after a submission, almost invariably the first submission.

## Testing

TBD

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

## Checklist

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you added or removed a file deployed with the application:

- [ ] I have updated AppArmor rules to include the change

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [ ] These changes do not require documentation

### If you added or updated a production code dependency:

Production code dependencies are defined in:

- `admin/requirements.in`
- `admin/requirements-ansible.in`
- `securedrop/requirements/python3/securedrop-app-code-requirements.in`

If you changed another `requirements.in` file that applies only to development
or testing environments, then no diff review is required, and you can skip
(remove) this section.

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

2022-08-25 20:23 UTC, cfm requested changes
@zenmonkeykstop, I support this change and will be happy to review it!  However, in looking at the diff I'm surprised that no tests needed to be updated.  How would you feel about adding at least tests for:

1. no reply key generated (as previously intended) after `/lookup`; but
2. reply key generated (as now intended) after `/generate`?

2022-08-31 11:34 UTC, zenmonkeykstop commented
@cfm that's valid, it is a bit :thinking: that we can make a change like this with no test suite impact. Will add later.

2022-09-15 23:39 UTC, zenmonkeykstop commented
In lieu of adding tests, updated existing ones that check the relevant behavior - feel free to take a look @cfm

2022-09-19 18:02 UTC, cfm commented
Thanks, @zenmonkeykstop!  I'll review this week for v2.5.0.

2022-09-19 18:04 UTC, zenmonkeykstop commented
TBH I might not aim to have this in scope for 2.5.0. I think we need to do a bit more around key/account cleanup (especially for unused pending accounts) before a potential move to Sequoia, so maybe a 2.6.0? and then Sequoia in 2.7.0? Either way, no rush.

2022-09-27 01:00 UTC, cfm commented
The offer of `extra points` inspired me to draft a minimal [stress test](https://gist.github.com/cfm/c1e4840788ba07ac207205325d28e529) for the `/{,generate,create,lookup,submit,logout}` happy path.  I was indeed able to induce some stress, but I need to test further to determine:
1. whether this possibility precedes or is introduced by these changes; and
2. how much it matters.

2022-09-27 01:11 UTC, zenmonkeykstop commented
extra points ftw - how did it break?

2022-09-27 01:17 UTC, cfm commented
Updated above pending further investigation!

2022-09-28 00:04 UTC, cfm approved these changes, later dismissed
Approving per test plan, but leaving marked as draft pending the v2.5.0 code freeze.

- Check out this branch and run `make dev`
- [x] in another terminal, connect to the dev container with `docker exec -it securedrop-dev-0 bash` and verify that only the default dev source reply keys exist with `gpg --homedir /var/lib/securedrop/keys -k`

```sh-session
user@sd-dev:~/securedrop$ docker exec -it securedrop-dev-0 gpg --homedir /var/lib/securedrop/keys -k | grep "Source Key" | wc -l
3
```

- Create a new source via the SI, but do not submit anything

- [x] verify that no new key was created, with `gpg --homedir /var/lib/securedrop/keys -k`

```sh-session
user@sd-dev:~/securedrop$ docker exec -it securedrop-dev-0 gpg --homedir /var/lib/securedrop/keys -k | grep "Source Key" | wc -l
3
```

- [x] submit a message as the source and verify that a reply key was created

```sh-session
user@sd-dev:~/securedrop$ docker exec -it securedrop-dev-0 gpg --homedir /var/lib/securedrop/keys -k | grep "Source Key" | wc -l
4
```

- [x] log in to the JI and verify that the source is listed and a reply can be sent
- [x] on the SI, verify that the reply is displayed correctly
- [x] submit another message and verify that a new reply key was *not* created

```sh-session
user@sd-dev:~/securedrop$ docker exec -it securedrop-dev-0 gpg --homedir /var/lib/securedrop/keys -k | grep "Source Key" | wc -l
4
```

- [x] on the JI, verify that another reply can be submitted.
- [x] log out of the SI, log back in as the same source, and verify that both replies can be read.

- [x] For extra points, try to break reply key generation by doing multiple simultaneous file submissions.

[Yes](https://github.com/freedomofpress/securedrop/pull/6490#issuecomment-1258836575), via a simple [stress test](https://gist.github.com/cfm/c1e4840788ba07ac207205325d28e529).  However, the same failure mode appears on `develop`.  I think it's just contention on the keyring, because I can reproduce it starting around 6 simultaneous (automated) submitters.  Let me know if you'd like a bug report for follow-up.

2022-09-28 16:17 UTC, cfm commented
Marking ready for review now that we have `release/2.5.0`.  @zenmonkeykstop, at your convenience, could you rebase this from `develop`, and then I'll re-approve and merge?

2022-10-31 20:02 UTC, cfm commented
@zenmonkeykstop, would you have time to rebase and conflict-resolve this branch this week, for me to take another (probably final!) look?

2022-12-20 23:40 UTC, cfm approved these changes
No substantive changes after rebase, so approving based on <https://github.com/freedomofpress/securedrop/pull/6490#pullrequestreview-1122850648>.  Thanks, @zenmonkeykstop!

2022-12-20 23:40 UTC, merged