Bring new fixtures to Journalist interface layout tests
freedomofpress/securedrop pull request #6504
Opened 2022-07-30 17:38 UTC by nabla-c0d3

## Status

Work in progress

## Description of Changes

TBD

2022-08-10 18:43 UTC, nabla-c0d3 commented on securedrop/tests/functional/pageslayout/test_journalist.py
> +@pytest.mark.parametrize("locale", list_locales())
Below I merged some of the "screenshot-taking" tests, so that the test suite would run faster.

2022-08-15 12:46 UTC, zenmonkeykstop commented on securedrop/tests/functional/pageslayout/test_journalist.py
> -        self._screenshot("journalist-admin_index_no_documents.png")
This screenshot is still referenced in the documentation.

2022-08-15 12:47 UTC, zenmonkeykstop commented on securedrop/tests/functional/pageslayout/test_journalist.py
> -        self._screenshot("journalist-index_javascript.png")
This screenshot is still referenced in the documentation

2022-08-15 12:53 UTC, zenmonkeykstop commented on securedrop/tests/functional/pageslayout/test_journalist.py
> -        self._screenshot("journalist-index_with_text.png")
This screenshot is still referenced in the docs.

2022-08-15 12:54 UTC, zenmonkeykstop requested changes
Good change overall, 3 of the tests that were removed generate screenshots that are still used in the docs, so they may need to be re-added (or the shots grabbed elsewhere in the test flow)

2022-08-15 14:09 UTC, nabla-c0d3 commented
@zenmonkeykstop Good catch - I didn't realize that this was how the screenshots were used. I've re-added the missing ones, and left thee changes as a separate [commit](https://github.com/freedomofpress/securedrop/pull/6504/commits/f4e9265e9da63594a556b426f25d49434098e976) so that it's easier to review. Thanks!

2022-08-16 13:57 UTC, zenmonkeykstop approved these changes
LGTM, thanks for the update.

2022-08-16 13:58 UTC, merged