updated mako from 1.0.7 to 1.2.2
freedomofpress/securedrop pull request #6535
Opened 2022-09-06 12:18 UTC by zenmonkeykstop

## Status

Ready for review

## Description of Changes

Updates `mako`, an `alembic` dependency, from v1.0.7 to 1.2.2

## Testing

- [ ] verify that CI is passing
- start a dev container on this branch with `cd securedrop/; ./bin/dev-shell`
- in the container run `cd securedrop; source ./bin/dev-deps && maybe_create_config_py`
- run the following commands to create an empty database:
  ```
  sudo mkdir -p /var/lib/securedrop/
  sudo chmod 0700 /var/lib/securedrop/
  sudo chown "$(id -u):$(id -g)" /var/lib/securedrop
  rm -f /var/lib/securedrop/db.sqlite
  sqlite3 /var/lib/securedrop/db.sqlite .databases > /dev/null
  ```
- [ ] verify that the command `alembic upgrade head` completes successfully
- [ ] verify that the command `alembic history` completes successfully
- [ ] verify that you can successfully downgrade to earlier alembic revisions and then upgrade again

## Deployment
 
n/a

## Checklist

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [x] These changes do not require documentation

### If you added or updated a production code dependency:

Choose one of the following:

- [x] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

2022-09-06 14:59 UTC, legoktm requested changes

2022-09-06 14:59 UTC, legoktm commented on securedrop/requirements/python3/securedrop-app-code-requirements.in
> +mako>=1.2.2
I would prefer we didn't add indirect dependencies to the requirements.in file, as it makes it confusing in the future whether a dependency is actually needed by us when upstreams change their dependencies.

Now that requirements.txt has been bumped, you should be able to remove it from requirements.in, re-run the update thing, and it'll fix the `via` to be just alembic, but keep it at 1.2.2.

2022-09-07 16:31 UTC, legoktm commented on securedrop/requirements/python3/securedrop-app-code-requirements.in
> +mako>=1.2.2
@zenmonkeykstop: I removed the mako line from this file, re-ran `make update-python3-dependencies` twice, and both times it did not downgrade `mako`, so I think it's good now.

2022-09-07 17:25 UTC, legoktm approved these changes
Going to wait until @zenmonkeykstop can look at my changes before I merge it. I also verified generating a new migration file works properly, which is the main usage of mako AIUI.

2022-09-07 18:02 UTC, zenmonkeykstop reviewed
Looks good to me @legoktm - merge at will!

2022-09-07 18:03 UTC, merged