Create explicit fixture for rqworker
freedomofpress/securedrop pull request #6551
Opened 2022-09-19 20:48 UTC by nabla-c0d3

## Status

Work in progress

## Description of Changes

TBD

2022-09-19 21:26 UTC, nabla-c0d3 commented on securedrop/tests/functional/conftest.py
>          # Sleep until the source and journalist web apps are up and running
The changes here are for helping with test flakiness

2022-09-27 06:19 UTC, legoktm reviewed
Looks good, though I only did a skim for now. Note that you'll have to rebase this once #6403 lands (I'll do a full review then).

2022-09-28 20:13 UTC, nabla-c0d3 commented
> Looks good, though I only did a skim for now. Note that you'll have to rebase this once #6403 lands (I'll do a full review then).

I rebased it just now

2022-09-30 16:02 UTC, legoktm requested changes
All looks good except `requeue_interrupted_jobs()` in `securedrop/scripts/rqrequeue` needs to be updated for the new required argument.

Surprisingly this is the first case I've encountered of LGTM actually pointing out a real issue, I wonder if pylint is not running on our scripts (will file a separate task for that).

2022-09-30 18:15 UTC, legoktm approved these changes
Very nice :)

2022-09-30 18:15 UTC, merged