Fetch SDConfig via explicit call and make config immutable
freedomofpress/securedrop pull request #6563
Opened 2022-09-25 08:51 UTC by nabla-c0d3

## Status

Work in progress

## Description of Changes

TBD

2022-12-01 20:10 UTC, legoktm requested changes
Awesome work! My comments are pretty minor things. Could you also expand the commit message (what you had in the PR description is good)?

And I think we can call this PR as fixing #5761.

2022-12-01 20:10 UTC, legoktm commented on securedrop/journalist_app/__init__.py
> +        static_folder=str(config.STATIC_DIR.absolute()),
static_folder can be a Path object, per https://flask.palletsprojects.com/en/2.0.x/api/

Note that template_folder cannot, I filed https://github.com/pallets/flask/issues/4892 for that.

2022-12-01 20:10 UTC, legoktm commented on securedrop/models.py
> +    timestamp = Column(DateTime, default=datetime.datetime.utcnow, nullable=True)
This is the current default, so was there a reason you made this change (mypy?)? Or is it just part of what I had suggested at the bottom of #6226?

2022-12-01 20:10 UTC, legoktm commented on securedrop/sdconfig.py
> +    final_default_locale = getattr(config_from_local_file, "DEFAULT_LOCALE", "en_US")
I think this should use FALLBACK_LOCALE instead of hardcoding en_US. Same with the next line.

2022-12-01 20:10 UTC, legoktm commented on securedrop/sdconfig.py
> +# TODO(AD): Should be removed or merged into SecureDropConfig or moved to i18n.py?
My impression is that this is a constant rather than a configuration setting, and so it should be kept wherever it's used (see my comments below).

2022-12-01 20:10 UTC, legoktm commented on securedrop/sdconfig.py
> +    # The following fields cannot be None if the DB engine is NOT sqlite
As a TODO, we really should drop all of these. Pretty sure practically we don't support anything other than sqlite, so there's really no point keeping it around. I'll file an issue for it.

2022-12-01 20:10 UTC, legoktm commented on securedrop/sdconfig.py
> +    SOURCE_TEMPLATES_DIR: Path
Same with dropping these paths that are really part of the application that people shouldn't be modifying...

2022-12-01 20:10 UTC, legoktm commented on securedrop/source_app/__init__.py
> +        static_folder=str(config.STATIC_DIR.absolute()),
Same here

2022-12-04 15:51 UTC, nabla-c0d3 commented on securedrop/models.py
> +    timestamp = Column(DateTime, default=datetime.datetime.utcnow, nullable=True)
Correct, if it was for mypy. When I run mypy locally, it complains if `nullable=True` is not present.

2022-12-04 16:29 UTC, nabla-c0d3 commented on securedrop/journalist_app/__init__.py
> +        static_folder=str(config.STATIC_DIR.absolute()),
Sounds good - I removed the call to `str()`

2022-12-04 16:29 UTC, nabla-c0d3 commented on securedrop/sdconfig.py
> +    final_default_locale = getattr(config_from_local_file, "DEFAULT_LOCALE", "en_US")
Done

2022-12-04 16:31 UTC, nabla-c0d3 commented on securedrop/sdconfig.py
> +    # The following fields cannot be None if the DB engine is NOT sqlite
Not supporting anything but sqlite would definitely simplify some of the code 👍.

2022-12-04 16:32 UTC, nabla-c0d3 commented on securedrop/sdconfig.py
> +    SOURCE_TEMPLATES_DIR: Path
I 100% agree that only settings that are meant to be modified by the user should be kept there.

2022-12-04 16:32 UTC, nabla-c0d3 commented on securedrop/sdconfig.py
> +# TODO(AD): Should be removed or merged into SecureDropConfig or moved to i18n.py?
I had to leave it in sdconfig.py so that it could be used as the default value for DEFAULT_LOCALE.

2022-12-04 16:33 UTC, nabla-c0d3 commented on securedrop/source_app/__init__.py
> +        static_folder=str(config.STATIC_DIR.absolute()),
Done

2022-12-04 16:33 UTC, nabla-c0d3 commented
I made the requested changes and expanded the commit message 👍. Thanks for the review!

2022-12-05 20:24 UTC, legoktm requested changes
Noticed that `securedrop/scripts/` needs to be updated.

2022-12-05 22:23 UTC, nabla-c0d3 commented
> Noticed that `securedrop/scripts/` needs to be updated.

Good catch... I updated them now.

2022-12-05 23:39 UTC, legoktm approved these changes
Awesome! This is all really great

2022-12-05 23:40 UTC, merged