ci: run flake8 for alembic migrations
freedomofpress/securedrop pull request #6590
Opened 2022-10-04 16:49 UTC by rahulXs

Signed-off-by: Rahul Sharma <rahulxsh@gmail.com>

## Status

Ready for review

## Description of Changes

Fixes #6576 

Changes proposed in this pull request: Update .flake8 file to include `securedrop/alembic/versions` and fix existing flake8 errors for alembic migrations.

## Testing

How should the reviewer test this PR?
NA

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing production instances.
2. New installs.

## Checklist

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made changes to `securedrop-admin`:

- [ ] Linting and tests (`make -C admin test`) pass in the admin development container

### If you made changes to the system configuration:

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

### If you added or removed a file deployed with the application:

- [ ] I have updated AppArmor rules to include the change

### If you made non-trivial code changes:

- [ ] I have written a test plan and validated it for this PR

Choose one of the following:

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation
- [ ] These changes do not require documentation

### If you added or updated a production code dependency:

Production code dependencies are defined in:

- `admin/requirements.in`
- `admin/requirements-ansible.in`
- `securedrop/requirements/python3/securedrop-app-code-requirements.in`

If you changed another `requirements.in` file that applies only to development
or testing environments, then no diff review is required, and you can skip
(remove) this section.

Choose one of the following:

- [ ] I have performed a diff review and pasted the contents to [the packaging wiki](https://github.com/freedomofpress/securedrop-debian-packaging/wiki)
- [ ] I would like someone else to do the diff review

2022-10-04 19:32 UTC, legoktm requested changes
Nice job! I left two small comments.

2022-10-04 19:32 UTC, legoktm commented on securedrop/alembic/versions/b7f98cfd6a70_make_filesystem_id_non_nullable.py
> +    # First we delete out of replies/seen_files/seen_messages (things that refer to sources)
The original text was correct: things (replies/seen_files/seen_messages) that refer to things (source_stars/submissions/replies) that refer to sources. Maybe that's a better way to phrase it?

2022-10-04 19:32 UTC, legoktm commented on securedrop/alembic/versions/2e24fc7536e8_make_journalist_id_non_nullable.py
> +                f"WHERE journalist_id IS NULL;"
Very minor, but you can remove the f from the new line because there are no variables being interpolated in.

2022-10-05 03:14 UTC, rahulXs commented
@legoktm thanks for the review. I've updated the comment text and removed `f` from the newline in fstring due to no variable interpolation.

2022-10-05 16:13 UTC, legoktm approved these changes
Awesome, I squashed it to one commit and will merge once CI passes. Congrats and thanks for your first contribution to SecureDrop! 🎆

2022-10-05 21:12 UTC, merged