Pre-build Python bytecode, don't run alembic as root
freedomofpress/securedrop pull request #6591
Opened 2022-10-04 18:39 UTC by legoktm

## Status

Ready for review

## Description of Changes

* Generate Python bytecode at install time, ensures they're all owned by root:root and that it doesn't need to be generated on the fly.
* Run alembic and mod_wsgi-express as www-data rather than root for additional hardening.

Refs <https://github.com/freedomofpress/securedrop-security/issues/84>.

## Testing

* [ ] Build new packages, try installing them, make sure nothing breaks. Then try a submission and log into the JI (should exercise enough code paths that the pyc isn't obviously broken)

## Deployment

Any special considerations for deployment? Not particularly.

## Checklist

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container
- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass
- [ ] I have written a test plan and validated it for this PR
- [ ] These changes do not require documentation

2022-10-04 19:01 UTC, legoktm commented
I tested everything except for logging into the JI, because the onion service keeps timing out for me :/

2022-10-04 19:34 UTC, zenmonkeykstop commented
@legoktm with this change, can we update the apparmor profile to make the __pycache__ dirs readonly for apache?

2022-10-04 21:03 UTC, legoktm commented
> @legoktm with this change, can we update the apparmor profile to make the **pycache** dirs readonly for apache?

Done but untested.

2022-10-05 14:45 UTC, zenmonkeykstop requested changes, later dismissed
Running the alembic tasks as www-data results in at least config.py being recompiled with `www-data` ownership. It might be worth dropping the "sudo -u www-data" for these and relying on existing logic to fix up ownership on the db after root does its thing.

2022-10-05 14:45 UTC, zenmonkeykstop commented on install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/files/usr.sbin.apache2
> +  /opt/venvs/securedrop-app-code/**/__pycache__/ r,
Basic application functionality unaffected by this change, :+1:

2022-10-05 14:45 UTC, zenmonkeykstop commented on install_files/securedrop-app-code/debian/postinst
> +            sudo -u www-data ${SDBIN}/alembic stamp 15ac9509fc68
running `dpkg-reconfigure` to hit this line in the postinst regenerates `/var/www/securedrop/__pycache__/config.cpython-38.pyc` with `www-data` the owner.

If I run a downgrade and then upgrade again, both as `www-data`, it also recompiles config.py.

2022-10-05 14:45 UTC, zenmonkeykstop commented on install_files/securedrop-app-code/debian/postinst
> +    py3compile "${SDVE}"
bytecode is regenerated with root ownership in default locations :+1:

2022-10-05 14:45 UTC, zenmonkeykstop commented on install_files/securedrop-app-code/debian/postinst
> +    sudo -u www-data ${SDBIN}/mod_wsgi-express module-config > /etc/apache2/mods-available/wsgi.load
is this necessary?

2022-10-05 15:58 UTC, legoktm commented
I dropped the `sudo -u www-data` part per review, I'll open a separate PR with that after some more testing.

2022-10-05 18:27 UTC, zenmonkeykstop approved these changes
LGTM, no impact on functionality and .pyc files are root-owned and not overwritten by Apache during a test source and journalist session.

2022-10-05 18:27 UTC, merged