Make venv use python3.9 opportunistically, but default to python3
freedomofpress/securedrop pull request #6685
Opened 2022-11-13 19:49 UTC by eaon

Our virtual environment generally assumes that developers use Debian stable - that's not necessarily the case though, so this commit introduces an opportunistic approach to using the same Python version.

## Testing

On a machine that defaults to a Python version higher than 3.9, but has 3.9 installed: remove your `.venv` folder:

- [ ] `make venv` creates a virtual environment with Python 3.9

## Checklist

- [x] I have written a test plan and validated it for this PR
- [x] These changes do not require documentation

2022-11-13 21:02 UTC, legoktm commented on devops/scripts/boot-strap-venv.sh
> +        "${VENV}/bin/pip" install -q -r "securedrop/requirements/python${PYTHON_VERSION::1}/develop-requirements.txt"
Cool trick, but I think we can just hardcode the 3 now. It's already hardcoded in other places too

2022-11-13 21:09 UTC, legoktm commented
Hmm, shouldn't we prefer 3.8 over 3.9 since that's what CI uses and what we use in production with focal? (I've been using 3.8 for that reason)

2022-11-21 14:08 UTC, legoktm requested changes
See above.

2022-11-28 16:51 UTC, legoktm commented
Code looks good, but shouldn't we prefer 3.8 over 3.9?

2022-12-21 14:34 UTC, eaon commented
Makes sense, disregard the branch name now, I changed it to use `python3.8` instead!

2023-01-04 00:13 UTC, legoktm approved these changes
LGTM!

2023-01-04 00:13 UTC, merged