Remove molecule from the package building process
freedomofpress/securedrop pull request #6754
Opened 2023-02-22 03:17 UTC by legoktm

## Status

Ready for review

## Description of Changes

Split into (currently) 5 commits:
* Pin dh-virtualenv from jammy, not impish
* Remove not-useful builder tests (see commit message for detailed rationale)
* Split and slim down test_securedrop_deb_package.py (again, see commit message)
* Re-organize ossec packaging to use debhelper and standard layout (basically the equivalent of https://github.com/freedomofpress/securedrop/pull/6544 but for OSSEC packages)
* Use plain container for package building, not molecule

Fixes #6706.

## Testing

* [ ] `make build-debs` without this PR, save the debs somewhere
* [ ] `make build-debs` with this PR.
* [ ] diffoscope shows no non-trivial diffs.

## Deployment

Any special considerations for deployment? No, diffoscope should give us confidence to a lack of changes. 

## Checklist

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass
- [ ] I have written a test plan and validated it for this PR

2023-02-22 19:56 UTC, legoktm commented
Discussed with Kev today, one thing to add either here or in documentation is what should be done with buildinfo files (see #6356) and investigate setting up a rebuilder to independently verify reproducibility.

2023-02-22 22:39 UTC, legoktm commented
mostly finished diffoscoping, in ossec-server, it's capturing the container hostname so it's not reproducible yet:
```
│ │ ├── ./var/ossec/etc/ossec.conf
│ │ │ @@ -1,13 +1,13 @@
│ │ │  <ossec_config>
│ │ │    <global>
│ │ │      <email_notification>yes</email_notification>
│ │ │      <email_to>root@localhost</email_to>
│ │ │      <smtp_server>127.0.0.1</smtp_server>
│ │ │ -    <email_from>ossecm@be0083033c5f</email_from>
│ │ │ +    <email_from>ossecm@c26ce720f917</email_from>
│ │ │    </global>
```

Also I think I unintentionally renamed the ossec.service unit to ossec-agent.service.

2023-02-23 16:41 UTC, legoktm commented
The current value is `<email_from>ossecm@focal-sd-generic-ossec-server</email_from>`, I think we can use a fixed hostname like `sd-ossec-builder` (similar to `sd-kernel-builder`).

2023-02-23 17:37 UTC, legoktm commented
Also I backed out the change to use debhelper's systemd support because it's probably best done after we move to compat 11. So the service units are installed exactly the same as before.

2023-02-24 17:33 UTC, legoktm commented
Some remaining TODOs:
* Add CI to verify all debs (except securedrop-app-code for now) are reproducible.
* Document that .buildinfo files need to be published (n.b. this should cover SDW too)

2023-03-07 01:42 UTC, cfm reviewed
I've read through this both commit- and diff-wise and think it looks fabulous, @legoktm.  The precedent and benefit of #6544 is evident!

I'll try to run through the test plan this week, next Monday at the latest.  In the meantime: do you see freedomofpress/securedrop-engineering#20 as a prerequisite for approving (in addition to documenting the goals and principles of) this work?

2023-03-07 01:42 UTC, cfm commented on builder/Dockerfile
> +FROM ubuntu:focal
This is one half of the documentation change @eloquence requested last week: removing <https://developers.securedrop.org/en/latest/dockerbuildmaint.html>.  The other half, per <https://github.com/freedomofpress/securedrop/pull/6754#issuecomment-1444097514>, is documenting the generation of `.buildinfo` files instead.

2023-03-07 18:16 UTC, legoktm commented
Thanks!

> I'll try to run through the test plan this week, next Monday at the latest. In the meantime: do you see [freedomofpress/securedrop-engineering#20](https://github.com/freedomofpress/securedrop-engineering/pull/20) as a prerequisite for approving (in addition to documenting the goals and principles of) this work?

No. Our current security posture/requirement is that we build debs in a dispVM that builds/executes a container, which doesn't change with this PR (just how the container is set up and what it does), my proposal is to drop the dispVM part, which is what the dep-check stuff is for (since you don't really need to worry about out of date containers in a dispVM), but that should be mostly independent to this.

And I'll work on the documentation stuff in the next few days.

2023-03-10 17:05 UTC, legoktm commented
Documentation PR: https://github.com/freedomofpress/securedrop-dev-docs/pull/40

2023-03-14 00:14 UTC, cfm commented on builder/Dockerfile
> +FROM ubuntu:focal
This is proposed in freedomofpress/securedrop-dev-docs#40.

2023-03-14 00:21 UTC, cfm approved these changes, later dismissed
I've run through a full set of builds according to the test plan, comparing packages built from `0fb3f24^` (as the parent of this branch, to filter out any noise from `develop`) and from this branch.  All look good.  Thanks, @legoktm, for the hints on what level of reproducibility, thus what size and kind of diff, to expect for each packge.

I've received a few OSSEC alerts *about* the new `ossec-server`:

```
Integrity checksum changed for: '/var/ossec/checksdconfig.py'
Permission change: 'rwxr-xr-x' to 'r-xr-x---'
```

```
Integrity checksum changed for: '/var/ossec/etc/ossec.conf'
Permission change: 'rw-r--r--' to 'r--r-----'
```

```
Integrity checksum changed for: '/var/ossec/etc/resolv.conf'
What changed:
1c1
< nameserver 10.139.1.1
---
> -e nameserver 10.139.1.1
```

```
Integrity checksum changed for: '/var/ossec/etc/ossec-init.conf'
What changed:
3c3
< DATE="Thu Mar 11 20:36:21 UTC 2021"
---
> DATE="Mon Apr 13 18:53:21 UTC 2020"
```

I've now reached `Max emails per hour reached.`  Assuming (a) that these diffs are expected, @legoktm, and (b) that alerts come through as usual overnight, I'll merge in the morning.

2023-03-14 03:36 UTC, legoktm commented
Hmm, the permissions changes are not intentional, let me poke at that tomorrow. (The DATE one is though)

2023-03-14 18:54 UTC, legoktm commented
The easiest way to verify the permission fixes is to use the `debdiff` tool (`devscripts` package in Debian/Fedora). Before today's commits, it looked like https://gist.github.com/legoktm/897ca3a06677385994311a96c8d98aa7 (where original-server is the deb from https://apt.freedom.press/pool/main/o/ossec.net/). It lists files as different if they have different perms/owners/names but ignores content.

After the fixperms fixes, it looks lke:
```
user@dev ~/g/f/s/b/focal> debdiff original-server.deb ossec-server_3.6.0+focal_amd64.deb
[The following lists of changes regard files as different if they have
different names, permissions or owners.]

Files in second .deb but not in first
-------------------------------------
-rw-r--r--  root/root   /usr/share/doc/ossec-server/changelog.gz
-rw-r--r--  root/root   DEBIAN/conffiles
-rw-r--r--  root/root   DEBIAN/md5sums

Files in first .deb but not in second
-------------------------------------
-rw-r--r--  root/root   /usr/share/doc/ossec-server/changelog.Debian
-rw-r--r--  root/root   /usr/share/lintian/overrides/ossec-server
-rw-r--r--  root/root   DEBIAN/templates
-rwxr-xr-x  root/root   DEBIAN/prerm

...
```

All of the remaining changes are expected and desired because they're actually files being added/removed.

2023-03-15 01:24 UTC, cfm approved these changes
Thanks, @legoktm.  I've `debdiff`ed and installed the new `ossec-{agent,server}` packages, and I'll merge tomorrow assuming (a) OSSEC alerts come through as usual overnight and (b) CircleCI comes back from the dead.

2023-03-15 01:26 UTC, cfm requested changes
Oops: can you rebase and resolve the conflicts with `develop` after #6739?

2023-03-20 23:21 UTC, cfm commented
Rebased from `develop` without changes.

2023-03-21 00:12 UTC, cfm approved these changes
After <https://github.com/freedomofpress/securedrop/pull/6754#pullrequestreview-1340506894>, OSSEC is happy, CI is happy, and the conflicts with `develop` are resolved—so I'm merging.  Thanks for this, @legoktm!

2023-03-21 00:12 UTC, merged