Clean Python cache in prerm only
freedomofpress/securedrop pull request #6782
Opened 2023-04-14 21:23 UTC by legoktm

## Status

Ready for review

## Description of Changes

We are currently cleaning the Python cache in the postinst and postrm, but that still leaves us with warnings from apt that non-empty `__pycache__` directories couldn't be deleted.

This mimics what dh-python does, which is to run py3compile in the postinst (already doing) and run py3clean in the prerm.

During a fresh install, only the postinst is triggered to compile the cache.

During an upgrade, first the prerm runs, removing the cache, then the new version is unpacked, then postinst goes, recreating the cache.

Fixes #6743.

## Testing

* [ ] Set up a 2.5.1 prod/staging install
* [ ] Run `make build-debs` with this PR, 
* [ ] Upgrade to the new 2.6.0~rc1 securedrop-app-code deb on the instance with `sudo apt install ./securedrop-app-code....deb`
* [ ] Observe no dpkg warnings during upgrade
* [ ] Check that `/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/passlib/` no longer exists
* [ ] Look through one or two other dependencies in the venv, verify the `__pycache__` folders were created and are owned by root.

## Deployment

Any special considerations for deployment? Considered, see above for explanation.

## Checklist

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass
- [ ] I have written a test plan and validated it for this PR
- [x] These changes do not require documentation

2023-04-14 21:24 UTC, legoktm commented
(just FYI I haven't actually tested this since I'm using my prod setup to test the other cron->systemd PR, but uh, it should work!)

2023-04-28 17:27 UTC, zenmonkeykstop commented
Tested by:
- setting up 2.5.2(current version) on prod VMs
- building packages locally and installing using upgrade scenario (as opposed to dpkg)

- [x] no warnings observed during install
- [ ] `.../passlib` still exists
- [ ] spot-checking `__pycache__` dirs, they do exist and are root-owned.

2023-04-28 17:27 UTC, zenmonkeykstop requested changes
`.../passlib` still exists so test plan not passing.

2025-05-07 21:21 UTC, eloquence commented
@legoktm 2 years old, still worth doing?

2025-05-08 22:48 UTC, legoktm commented
Probably not, it's mostly just cosmetic at this point. I'll close the issue too.

2025-05-08 22:48 UTC, closed without merging