build(build-debs*): log all output via `script`
freedomofpress/securedrop pull request #6787
Opened 2023-05-03 19:21 UTC by cfm

## Status

Ready for review

## Description of Changes

Towards #6774, wraps all `build-debs.sh` invocations in `script` and displays the filename of the transcript after its conclusion.

This should be easily replicable to `securedrop-builder`.

## Testing

- Run one or more of the `make build-debs*` targets
- `^C` freely
- [ ] A transcript `build/${TIMESTAMP}-${TARGET}.log` is created...
- [ ] ...and is legible

## Deployment

Developer-only; no deployment considerations.

## Checklist

### If you made non-trivial code changes:

Choose one of the following:

- I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-docs) for these changes, or will do so later
- I would appreciate help with the documentation
- [x] These changes do not require documentation

...because they are self-documenting (-prompting), but I will probably document them anyway after merge.  :-)

2023-05-04 02:39 UTC, legoktm requested changes
On a technical level this is great. Some things that would make it even better:

1. Can we use a better filename? `2023-05-03T22:24:29-04:00-build-debs.log` is a bit...terrible (especially the colons :p). Looking through build-logs, I think something like `YYYYMMDD-securedrop-X.Y.Z.log` and similar for the OSSEC packages. I don't think we need to label it differently whether or not tests were run, since that'll be in the log itself (or not). Also, will this overwrite the file if it already exists? Or append? If it's the latter, we should probably use a complete timestamp instead of just the day.
2. Can we print the commit sha1/tag we are building from?
3. (bonus points) Can we verify said sha1/tag is signed? But in some optional way so if you're doing local test builds it just prints e.g. "WARNING: building from unsigned commit/tag" or something.

No 2 and 3 could probably be done in build-debs.sh?

With those 3 then I think building packages would be 1) clone repo 2) checkout commit/tag 3) `make build-debs` and nothing else.

Minor: curious why you made `$SCRIPT_OUTPUT_EXT` a variable instead of just hardcoding it.

2023-05-05 01:50 UTC, cfm commented
Thanks, @legoktm!

On Wed, May 03, 2023 at 07:39:15PM -0700, Kunal Mehta wrote:
> 1. Can we use a better filename?
> `2023-05-03T22:24:29-04:00-build-debs.log` is a bit...terrible
> (especially the colons :p). Looking through build-logs, I think
> something like `YYYYMMDD-securedrop-X.Y.Z.log` and similar for the
> OSSEC packages. I don't think we need to label it differently whether
> or not tests were run, since that'll be in the log itself (or not).
> 2. Can we print the commit sha1/tag we are building from?
> 3. (bonus points) Can we verify said sha1/tag is signed? But in some optional way so if you're doing local test builds it just prints e.g. "WARNING: building from unsigned commit/tag" or something.

My goal here was really just "${TIMESTAMP}-${TARGET}.${EXT}".  :-)  But
these are all good, worthwhile suggestions.  Unless you really want to
combine them, I'd prefer to simplify (1) in this pull request and defer
(2) and (3) to a separate one, since they go beyond the original #6774.
In any case, I can make these changes next week.


> Minor: curious why you made `$SCRIPT_OUTPUT_EXT` a variable instead of
> just hardcoding it.

DRYer until proven otherwise, is my instinct.  :-)

2023-05-05 19:15 UTC, legoktm commented
> Unless you really want to combine them, I'd prefer to simplify (1) in this pull request and defer (2) and (3) to a separate one

Fine with me :)

2023-05-09 23:12 UTC, cfm commented
Back to you, @legoktm, with the rest of your suggestions filed in #6792.

2023-05-10 16:47 UTC, legoktm approved these changes
Awesome, works as desired!

2023-05-10 16:47 UTC, merged