Code Improvements for Pending Source Management
freedomofpress/securedrop pull request #6793
Opened 2023-05-10 14:59 UTC by nathandyer

## Status

Work in progress

## Description of Changes

This is a bite-size PR based on additional changes requested in PR #6785

## Testing

- [ ] CI passes

From my perspective, I don't believe additional testing beyond making sure the tests pass are needed, as this does not make any substantial change to the logic or functionality.

## Checklist

### If you made changes to the server application code:
- [x] Linting (`make lint`) and tests (`make test`) pass in the development container

2023-05-23 21:08 UTC, cfm requested changes, later dismissed
I'll defer to @legoktm to review the changes he requested in <https://github.com/freedomofpress/securedrop/pull/6785#pullrequestreview-1419188856>.  But I thought I'd note, @nathandyer, that this branch is currently failing `lint`.

2023-05-23 21:08 UTC, cfm commented on securedrop/management/sources.py
> +    the n newest source accounts (as provided by args.keep_most_recent).
Suggest:

```suggestion
    the `args.keep_most_recent` newest source accounts.
```

2023-05-24 14:09 UTC, nathandyer commented
Sorry about that @cfm, apparently it wanted one extra blank line :upside_down_face: 

Linter should now be happy, and this should be ready for review whenever @legoktm has a chance. Thanks both!

2023-05-24 18:14 UTC, zenmonkeykstop approved these changes
Changes look good based on visual review, thanks for squishing :)

2023-05-24 18:15 UTC, merged

2023-05-25 19:01 UTC, legoktm commented
Belated 👍🏾 from me :)