loaddata: Allow increasing the size of submitted files
freedomofpress/securedrop pull request #7016
Opened 2023-10-18 18:47 UTC by legoktm

## Status

Ready for review

## Description of Changes

This would make it easier to get rough benchmarks of encryption steps.

This is pretty quick/rough, not sure if there's a better way we want to go about this. Note that this would need to be manually applied to a 2.6.0 install to get numbers for gpg.

## Testing

How should the reviewer test this PR?

* [ ] Try `time ./loaddata.py --file-size 500000000`, etc.

## Deployment

Any special considerations for deployment? No

## Checklist

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

2023-10-19 15:05 UTC, zenmonkeykstop requested changes

2023-10-19 15:05 UTC, zenmonkeykstop commented on securedrop/loaddata.py
> +        io.BytesIO(b"A" * size),
We compress then encrypt, so this will compress down to pretty much nothing before further processing, making it less useful for timing encryption or file transfers. Consider adding some randomness?

2023-10-19 16:21 UTC, legoktm commented on securedrop/loaddata.py
> +        io.BytesIO(b"A" * size),
Hmm, good point. Also there's a lot of overhead from SecureTemporaryFile. Maybe just a simple benchmarking script that just benchmarks exactly what we want (GPG vs redwood) would be better. Let me try to come up with something...

2023-10-26 21:04 UTC, legoktm commented
I don't want to merge this anymore. I created a separate benchmark script, which we could or could not merge, but IMO probably not.

2023-10-26 21:04 UTC, closed without merging