Support podman in `make dev-tor`
freedomofpress/securedrop pull request #7163
Opened 2024-05-24 18:45 UTC by legoktm

## Status

Ready for review

## Description of Changes

Unfortunately `podman volume` and `docker volume` are not identical, podman will (sensibly) error if you try to create a volume that already exists unless you pass `--ignore`, which docker doesn't support.

So we conditionally add the needed flag depending on which tool we're using.

## Testing

* [x] Visual review
* [ ] Run `make dev-tor` twice under docker, make sure it works
* [ ] Run `make dev-tor` twice under podman, make sure it works (I've done this laready)

## Deployment

Any special considerations for deployment? n/a, dev only

## Checklist

- [x] These changes do not require documentation

2024-06-03 10:01 UTC, deeplow requested changes
Thanks for finding this, at the time when I added the onion persistence I guess I did not realize podman was also supported. The solution didn't work for me so I proposed an alternative.

There's also another thing that needs to be provider-agnostic: the [make clean](https://github.com/freedomofpress/securedrop/pull/7124/files#diff-f069c7d8fd97be173c9a83b9c56b6cc869029c356cfd3ae8cff162d7efbe083cR41).

2024-06-03 10:01 UTC, deeplow commented on securedrop/bin/dev-shell
> +        $DOCKER_BIN volume create sd-onion-services $(if [ "$DOCKER_BIN" = "podman" ]; then echo "--ignore"; fi)
Unfortunately I don't see this option on my podman version (4.3.1) nor [on the docs](https://docs.podman.io/en/v4.4/markdown/options/volume.html). Maybe we can make it idempotent like this instead:

```suggestion
        $DOCKER_BIN volume inspect sd-onion-services -f " " || $DOCKER_BIN volume create sd-onion-services
```

2024-06-03 14:44 UTC, legoktm commented on securedrop/bin/dev-shell
> +        $DOCKER_BIN volume create sd-onion-services $(if [ "$DOCKER_BIN" = "podman" ]; then echo "--ignore"; fi)
Ah, it's documented at https://docs.podman.io/en/v4.4/markdown/podman-volume-create.1.html#ignore but yeah, it's new in 4.4. Will switch to your idea for 4.3 compat.

2024-06-03 21:58 UTC, legoktm commented
Thanks for the suggestion, now applied and fixed `make clean` as well.

2024-06-04 13:24 UTC, deeplow commented
Thanks for the fixes. I was reviewing this but got blocked by https://github.com/freedomofpress/securedrop/issues/7174.

2024-07-18 11:18 UTC, deeplow commented
> Thanks for the fixes. I was reviewing this but got blocked by https://github.com/freedomofpress/securedrop/issues/7174.

The above got resolved. However, I am having further challenges with podman, which seems to be beyond just `make dev-tor`, since it also fails with `make dev`.

Here's some truncated part of the output or `USE_PODMAN=1 make dev`

```
[...]

Exposed services will be available on localhost at
Source interface: http://127.0.0.1:8080
Journalist interface: http://127.0.0.1:8081
************************************************************
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
Unable to replace /dev/random
Starting to build Rust code
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.25s
Copying libredwood.so into package

[...]
Successfully installed redwood-0.1.0
WARNING: You are using pip version 21.1.1; however, version 24.1.2 is available.
You should consider upgrading via the '/opt/venvs/securedrop-app-code/bin/python3 -m pip install --upgrade pip' command.
███ Generating securedrop/config.py...

sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
make: *** [Makefile:250: dev] Error 1
```

Do you know what could be going on? I was on a disposable debian-12 VM on Qubes. Then I installed `make` and `podman` and ran  `USE_PODMAN=1 make dev`.

2024-09-25 09:32 UTC, deeplow approved these changes
LGTM. Approving based on visual inspection alone since I [can't seem to run this](https://github.com/freedomofpress/securedrop/issues/7235). This a minor dev-facing (non-default) option, so I'd say this can be fine.

However, it would be nice if someone else could test:
>   * [ ]  Run `make dev-tor` twice under docker, make sure it works
>   * [ ]  Run `make dev-tor` twice under podman, make sure it works (I've done this laready)

2024-12-20 19:10 UTC, legoktm commented
(Just a rebase to pick up the new CI jobs)

2024-12-20 20:34 UTC, merged