ci(translation): save screenshots as workflow artifacts
freedomofpress/securedrop pull request #7240
Opened 2024-10-04 23:24 UTC by cfm

## Status

Ready for review

## Description of Changes

Fixes #7237 by saving the screenshots generated by `make translation-test` as CI artifacts for 24 hours, for the following reasons:
1. `make translation-test` generates them no matter what, so we might as well make them inspectable.
2. #7237 occurs only locally, where this code path is rarely used; let's take advantage of CI exercising it.
3. This points towards perhaps even updating Weblate's copy of screenshots directly from these tests run nightly on `develop`.

## Testing

- [ ] Visual review.
- [ ] Inspect a couple of languages and confirm that their screenshots are correct.
- [ ] 24 hours is a reasonable retention period for ~100 MB of screenshots per run.

## Deployment

CI-only; no deployment considerations.

2024-10-07 18:11 UTC, legoktm requested changes
See inline comment.

I retriggered CI so there are artifacts that can be downloaded from https://github.com/freedomofpress/securedrop/actions/runs/11190459190 - but when I looked at some of the `el` and `de_DE` screenshots, they were all in English. (Or did I just happen to look at the wrong screenshots?)

2024-10-07 18:11 UTC, legoktm commented on .github/workflows/translation.yml
> +          retention-days: 1
Given that this job is run pretty rarely, I think 30 or even the default of 90 days is probably better. I'd only want to limit it if we start running out of space.

1 is too short given that no one reviewed this PR in time and they've already expired 🙃

2024-10-07 21:38 UTC, cfm commented
Good catch, @legoktm.  I'm looking into this in #7241.

2024-10-07 23:55 UTC, cfm commented on .github/workflows/translation.yml
> +          retention-days: 1
I've gotten rid of `retention-days` altogether in b3807124b86d8bc3dde25aeb69dad10df895c0b7.

2024-10-07 23:57 UTC, cfm commented
The fixes are in as of <https://github.com/freedomofpress/securedrop/issues/7241#issuecomment-2398211481>.  Two cheers for putting rarely-exercised code paths in CI!  Back to you, @legoktm.

2024-10-11 23:45 UTC, cfm commented
I wrestled with this some more today and found another problem with how the `firefox_web_driver` fixture was parameterized, which I've refactored in 7900e21b6326e6b86cb0ee145a15bed7f9fb67ed.  Back to you, @legoktm.

2024-10-16 15:59 UTC, legoktm commented
When I download `screenshots-de_DE` from https://github.com/freedomofpress/securedrop/actions/runs/11300734349, I see three subfolders, `de-DE`, `de_DE`, and `en-US`. So somewhere the dash is being normalized differently?

And...the de screenshots are still in English :/

2024-11-20 23:59 UTC, cfm commented
The good news is that the screenshots are being captured correctly.  The bad news is that the tests themselves still aren't (and haven't been) parameterized fully with the intended locale.  I'm looking into it.

2024-11-21 20:45 UTC, cfm commented
I found a couple more fundamental parameterization problems yesterday and today, for which I've just force-pushed fixes.  I'm going to monitor `translation-tests` for failing string checks before this is ready for another review.

2024-11-22 01:28 UTC, legoktm commented
I'd be happy to approve parts of this in separate PRs if that would be easier for you. e.g. the saving as artifacts part is totally fine and good to go, same with some of the other intermediate fixes.

2024-11-22 05:05 UTC, cfm commented
Thanks, @legoktm.  As of 6c9917c771187bf9ac4c08dc46df35d367245986 I've now got this sorted for the Journalist Interface in Firefox.  Tomorrow I should be able to fix up the Source Interface in Tor Browser the same way.  If not, I'll split it between the two interfaces.

2024-11-25 19:11 UTC, cfm commented
Ready here for the Journalist Interface.  The Source Interface I've deferred to #7354.

2024-11-25 22:59 UTC, legoktm approved these changes
Awesome, JI side looks good; thanks!

2024-11-25 23:03 UTC, merged