build: add `dev-get-id`, `dev-enter`, and `dev-load-data` targets
freedomofpress/securedrop pull request #7278
Opened 2024-10-24 22:54 UTC by cfm

## Status

Ready for review, but posting mostly for feedback.  If we want this, I'll see if I can make it agnostic between Docker and Podman.

## Description of Changes

Adds some helper Make targets working with a running `make dev[-tor]` container:
1. `dev-get-id` looks up the container ID
2. `dev-enter` starts a shell in the running container
3. `dev-load-data` runs `loaddata.py` in the running container

## Testing

Play around with it and let me know if this is worth polishing.

## Deployment

Development-only.

2024-10-25 18:03 UTC, legoktm commented
I have an alias of "sdshell" set to `podman exec --user=root -it (podman ps --filter name=securedrop --format '{{.ID}}') bash`. So +1 from me.

2025-04-16 18:26 UTC, legoktm requested changes
Looks good functionally but let's add podman support too please :)

2025-05-01 00:04 UTC, cfm commented
Done in 1a2602cd73391f8a589b03a646f4ad3e3e5be1ee.

2025-05-08 14:55 UTC, legoktm requested changes

2025-05-08 14:55 UTC, legoktm commented on Makefile
> +ifdef $(USE_PODMAN)
This didn't work for me, per https://www.gnu.org/software/make/manual/html_node/Conditional-Syntax.html I think it needs to be the name of the variable, not the value, so:

```suggestion
ifdef USE_PODMAN
```

and that did work for me.

2025-05-08 14:55 UTC, legoktm commented on Makefile
> +		$(shell make dev-get-id) \
This internal `make` command is outputting `make[1]: Entering directory /home/user/github/freedomofpress/securedrop ae8314c6d60a make[1]: Leaving directory /home/user/github/freedomofpress/securedrop`

so then obviously podman fails with: `Error: no container with name or ID "make[1]:" found: no such container`.

Solution appears to be:

```suggestion
		$(shell make -s dev-get-id) \
```

2025-05-08 14:55 UTC, legoktm commented on Makefile
> +		$(shell make dev-get-id) \
```suggestion
		$(shell make -s dev-get-id) \
```

2025-05-08 14:55 UTC, legoktm commented on Makefile
> +		./loaddata.py
can we add an $(ARGS) or something here? To pass e.g. `--random-file-size`.

2025-05-13 00:02 UTC, cfm commented on Makefile
> +		$(shell make dev-get-id) \
Fixed in c15991b48a04b516b62ad61450173968a8402aaf.

2025-05-13 00:03 UTC, cfm commented on Makefile
> +		$(shell make dev-get-id) \
Fixed in c15991b48a04b516b62ad61450173968a8402aaf.

2025-05-13 00:03 UTC, cfm commented on Makefile
> +ifdef $(USE_PODMAN)
Added in e0c1f3783984c579e55d4e7167a37e88d95890e5.

2025-05-13 00:05 UTC, cfm commented on Makefile
> +		./loaddata.py
Added in c15991b48a04b516b62ad61450173968a8402aaf.

2025-05-13 00:07 UTC, cfm commented
Whoops; sorry for the sloppiness there.  Should be all fixed up, @legoktm.

2025-05-13 19:50 UTC, legoktm approved these changes
LGTM, thanks!

2025-05-13 19:55 UTC, merged