Drop setting vm.heap_stack_gap and net.ipv4 sysctl flags
freedomofpress/securedrop pull request #7324
Opened 2024-11-01 21:38 UTC by legoktm

## Status

Ready for review

## Description of Changes

These are now set via the securedrop-grsec metapackage (see <https://github.com/freedomofpress/kernel-builder/pull/55>).

Refs #7323.

## Testing

How should the reviewer test this PR?

* [ ] visual review; compare that same flags are moved via https://github.com/freedomofpress/kernel-builder/pull/55

## Deployment

Any special considerations for deployment? 

This can only be deployed after a kernel with https://github.com/freedomofpress/kernel-builder/pull/55 is released stable. It's safe to merge ahead of time though.

## Checklist

- [ ] [Configuration tests](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) pass

2024-11-04 23:47 UTC, zenmonkeykstop requested changes, later dismissed
kernel-builder change looks good, but unless there's a compelling reason I'd keep the testinfra check.

2024-11-04 23:47 UTC, zenmonkeykstop commented on molecule/testinfra/common/test_system_hardening.py
> -@pytest.mark.parametrize(
IMO keeping the testinfra checks makes sense, in case the metapackage-set values get borked somehow.

2024-11-04 23:47 UTC, zenmonkeykstop commented on molecule/testinfra/common/test_grsecurity.py
> -        ("vm.heap_stack_gap", 1048576),
(repeat) IMO keeping the testinfra checks makes sense, in case the metapackage-set values get borked somehow.

2024-11-06 20:31 UTC, legoktm commented on molecule/testinfra/common/test_system_hardening.py
> -@pytest.mark.parametrize(
OK, happy to leave it in for now but long-term I think we don't want to run into needing to constantly keep this repo updated if we change things in kernel-builder (but I doubt we'll be changing that many sysctl flags).

2024-11-06 20:49 UTC, legoktm commented
This should fail CI now because we haven't built new kernel packages yet, I will see about doing some today or tomorrow.

2024-11-19 21:33 UTC, legoktm commented
The error is: `sed -i '/^vm\\.heap_stack_gap/d' /etc/sysctld.conf", "sed: can't read /etc/sysctld.conf: No such file or directory`

which I guess is an install order issue in that we're installing the new kernel before we try setting grsec kernel flags, so there's no sysctld.conf yet. Let me guard it with an if exists check in the metapackage.

2024-11-19 21:43 UTC, legoktm commented
kernel-builder fix: https://github.com/freedomofpress/kernel-builder/pull/57

2024-11-20 01:31 UTC, cfm commented
I've merged freedomofpress/kernel-builder#57, @legoktm, and I'll be happy to re-review this with kernels rebuilt with it.  (Let me know if you'd like me to build them tomorrow.)

2024-11-21 21:12 UTC, cfm approved these changes
Looks good after 37f182724bfc685b5bb1c43fd35c405290c3ff66 and freedomofpress/securedrop-apt-test#258.  Thanks, @legoktm.

2024-11-21 21:16 UTC, merged